### ISSUE TITLE
Cannot compile using clang 3.7.0

### ISSUE THREAD

**Issue by RiJo** [RiJo/dus#3]
The souce compiles using gcc-4.9 and gcc-5.3, but it won't compile using clang-3.7:

```
$ CXX=clang make
clang -std=c++14 -Wall -Werror -lpthread src/main.cpp -o dus
In file included from src/main.cpp:2:
In file included from src/fs.hpp:4:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/string:40:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/char_traits.h:39:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/stl_algobase.h:71:
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/predefined_ops.h:123:31: error: indirection requires pointer operand
      ('fs::file_info' invalid)
        { return bool(_M_comp(*__it1, *__it2)); }
                              ^~~~~~
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/functional:1981:27: note: in instantiation of function template specialization
      '__gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (const fs::file_info &, const fs::file_info &)> >::operator()<fs::file_info, fs::file_info>' requested here
        using _Invoke = decltype(__callable_functor(std::declval<_Functor&>())
                                 ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/functional:1990:2: note: in instantiation of template type alias '_Invoke' requested here
        using _Callable
        ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/functional:2057:30: note: in instantiation of template type alias '_Callable' requested here
               typename = _Requires<_Callable<_Functor>, void>>
                                    ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/functional:2058:2: note: in instantiation of default argument for
      'function<__gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (const fs::file_info &, const fs::file_info &)> > >' required here
        function(_Functor);
        ^~~~~~~~
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/predefined_ops.h:130:14: note: while substituting deduced template arguments into
      function template 'function' [with _Functor = __gnu_cxx::__ops::_Iter_comp_iter<std::function<bool (const fs::file_info &, const fs::file_info &)> >, $1 = (no value)]
    { return _Iter_comp_iter<_Compare>(__comp); }
             ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/stl_algo.h:4729:54: note: in instantiation of function template specialization
      '__gnu_cxx::__ops::__iter_comp_iter<std::function<bool (const fs::file_info &, const fs::file_info &)> >' requested here
      std::__sort(__first, __last, __gnu_cxx::__ops::__iter_comp_iter(__comp));
                                                     ^
src/main.cpp:275:10: note: in instantiation of function template specialization 'std::sort<__gnu_cxx::__normal_iterator<fs::file_info *, std::vector<fs::file_info,
      std::allocator<fs::file_info> > >, std::function<bool (const fs::file_info &, const fs::file_info &)> >' requested here
    std::sort(files.begin(), files.end(), comparators[order_by]);
         ^
1 error generated.
Makefile:19: recipe for target 'dus' failed
make: *** [dus] Error 1
```
